import { ScanResult } from "./mockData";
import { resolveBand, labelForBand } from "./scoring";

/**
 * Build a plain-text scan report suitable for download or copy/paste — the
 * kind of artefact you'd attach to a support ticket or hand to IT.
 */
export function buildReport(result: ScanResult): string {
  const lines: string[] = [];
  const ssid = result.wifiCurrentConnection?.ssid || result.networkName;
  const band = resolveBand(result);
  const verdict = labelForBand(band);

  lines.push("═══════════════════════════════════════════════");
  lines.push("  NETTRUST SCAN REPORT");
  lines.push("═══════════════════════════════════════════════");
  lines.push("");
  lines.push(`Network:      ${ssid}`);
  lines.push(`Type:         ${result.networkType}`);
  lines.push(`Verdict:      ${verdict}`);
  lines.push(`Trust Score:  ${band === "unknown" ? "Unverified" : `${result.trustScore}/100`}`);
  if (result.confidence != null) {
    lines.push(`Confidence:   ${Math.round(result.confidence * 100)}% of checks verified`);
  }
  if (result.publicIp) lines.push(`Public IP:    ${result.publicIp}`);
  if (result.ipReputation) {
    lines.push(`ISP:          ${result.ipReputation.org}`);
    lines.push(`Location:     ${result.ipReputation.city}, ${result.ipReputation.country}`);
    lines.push(`IP Type:      ${result.ipReputation.ipType}`);
  }
  lines.push(`Scanned:      ${new Date().toISOString()}`);
  lines.push("");

  const failed = result.checks.filter((c) => c.passed === false);
  const warnings = result.checks.filter((c) => c.passed === null);
  const passed = result.checks.filter((c) => c.passed === true);

  if (failed.length > 0) {
    lines.push(`── PROBLEMS FOUND (${failed.length}) ─────────────────────`);
    failed.forEach((c) => {
      lines.push(`  ✗ ${c.name}`);
      lines.push(`    ${c.status}`);
      if (c.evidence) {
        Object.entries(c.evidence).forEach(([k, v]) => {
          lines.push(`    ${k}: ${v}`);
        });
      }
      lines.push("");
    });
  }
  if (warnings.length > 0) {
    lines.push(`── COULDN'T VERIFY (${warnings.length}) ──────────────────`);
    warnings.forEach((c) => {
      lines.push(`  ⚠ ${c.name}: ${c.status}`);
    });
    lines.push("");
  }
  lines.push(`── PASSED (${passed.length}) ────────────────────────────`);
  passed.forEach((c) => lines.push(`  ✓ ${c.name}`));
  lines.push("");
  lines.push("───────────────────────────────────────────────");
  lines.push("Generated by NetTrust · netrust.lovable.app");
  return lines.join("\n");
}
