import { useState, useCallback } from "react";
import { ShieldAlert } from "lucide-react";
import ScanButton from "@/components/ScanButton";
import ResultsScreen from "@/components/ResultsScreen";
import HistoryScreen from "@/components/HistoryScreen";
import MoreScreen from "@/components/MoreScreen";
import SplashScreen from "@/components/SplashScreen";
import ConsentScreen from "@/components/ConsentScreen";
import Toast from "@/components/Toast";
import BottomNav from "@/components/BottomNav";
import { ScanResult } from "@/lib/mockData";
import { createFingerprint, compareAndStoreFingerprint, FingerprintComparison, clearFingerprints } from "@/lib/networkFingerprint";
import { COMPLIANCE, formatComplianceRef, CHECK_COUNT } from "@/lib/compliance";
import type { HistoryEntry } from "@/components/HistoryScreen";

type AppState = "idle" | "scanning" | "results";

function generateReport(result: ScanResult): string {
  const lines: string[] = [];
  const ssid = result.wifiCurrentConnection?.ssid || result.networkName;
  lines.push("═══════════════════════════════════════════════");
  lines.push("  NETTRUST SCAN REPORT");
  lines.push("  WiFi Security Assessment");
  lines.push("═══════════════════════════════════════════════");
  lines.push("");
  lines.push(`Network:      ${ssid}`);
  lines.push(`Type:         ${result.networkType}`);
  lines.push(`Trust Score:  ${result.trustScore}/100`);
  if (result.publicIp) lines.push(`Public IP:    ${result.publicIp}`);
  if (result.ipReputation) {
    lines.push(`ISP:          ${result.ipReputation.org}`);
    lines.push(`Location:     ${result.ipReputation.city}, ${result.ipReputation.country}`);
    lines.push(`IP Type:      ${result.ipReputation.ipType}`);
  }
  lines.push(`Scanned:      ${new Date().toISOString()}`);
  lines.push("");

  const failed = result.checks.filter(c => c.passed === false);
  const warnings = result.checks.filter(c => c.passed === null);
  const passed = result.checks.filter(c => c.passed === true);

  // NIST CSF coverage summary
  lines.push("── NIST CSF 2.0 COVERAGE ──────────────────────");
  for (const fn of ["Identify", "Protect", "Detect"] as const) {
    const inFn = result.checks.filter(c => COMPLIANCE[c.id]?.nist.fn === fn);
    const passedInFn = inFn.filter(c => c.passed === true).length;
    lines.push(`  ${fn}: ${passedInFn}/${inFn.length} passed`);
  }
  lines.push("");

  if (failed.length > 0) {
    lines.push(`── THREATS DETECTED (${failed.length}) ─────────────────────`);
    failed.forEach(c => {
      lines.push(`  ✗ ${c.name}`);
      lines.push(`    Status: ${c.status}`);
      const ref = formatComplianceRef(c.id);
      if (ref) lines.push(`    Ref:    ${ref}`);
      if (c.evidence) {
        Object.entries(c.evidence).forEach(([k, v]) => {
          lines.push(`    ${k}: ${v}`);
        });
      }
      lines.push("");
    });
  }
  if (warnings.length > 0) {
    lines.push(`── WARNINGS (${warnings.length}) ──────────────────────────`);
    warnings.forEach(c => {
      lines.push(`  ⚠ ${c.name}: ${c.status}`);
      const ref = formatComplianceRef(c.id);
      if (ref) lines.push(`    Ref: ${ref}`);
    });
    lines.push("");
  }
  lines.push(`── PASSED (${passed.length}) ────────────────────────────`);
  passed.forEach(c => lines.push(`  ✓ ${c.name}`));
  lines.push("");
  lines.push("───────────────────────────────────────────────");
  lines.push("Frameworks: NIST CSF 2.0 · OWASP Top 10 (2021) · CWE");
  lines.push("Generated by NetTrust v4.0");
  lines.push("This report is for informational purposes only.");
  return lines.join("\n");
}

const Index = () => {
  const [hasConsent, setHasConsent] = useState(() => {
    return localStorage.getItem("nettrust_consent") === "true";
  });
  const [showSplash, setShowSplash] = useState(true);
  const [state, setState] = useState<AppState>("idle");
  const [activeTab, setActiveTab] = useState("scan");
  const [result, setResult] = useState<ScanResult | null>(null);
  const [fingerprintResult, setFingerprintResult] = useState<FingerprintComparison | null>(null);
  const [autoScan, setAutoScan] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "warning" } | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>(() => {
    try {
      const stored = localStorage.getItem("nettrust_history");
      if (stored) {
        const parsed = JSON.parse(stored);
        return parsed.map((e: any) => ({ ...e, timestamp: new Date(e.timestamp) }));
      }
    } catch {}
    return [];
  });

  // Auto-start scan after splash dismisses
  const handleSplashDismiss = useCallback(() => {
    setShowSplash(false);
    setAutoScan(true);
    setState("scanning");
  }, []);

  const handleScanComplete = useCallback((scanResult: ScanResult) => {
    setResult(scanResult);
    setState("results");
    setAutoScan(false);

    // Create and compare network fingerprint
    const ssid = scanResult.wifiCurrentConnection?.ssid || scanResult.networkName;
    const fp = createFingerprint(
      ssid,
      scanResult.publicIp,
      scanResult.checks,
      scanResult.ipReputation ? {
        org: scanResult.ipReputation.org,
        asn: scanResult.ipReputation.asn,
        city: scanResult.ipReputation.city,
      } : null,
      scanResult.trustScore,
    );
    const comparison = compareAndStoreFingerprint(fp);
    setFingerprintResult(comparison);

    // Save to history
    const newEntry: HistoryEntry = {
      id: crypto.randomUUID(),
      result: scanResult,
      timestamp: new Date(),
    };
    setHistory((prev) => {
      const updated = [newEntry, ...prev].slice(0, 50);
      try { localStorage.setItem("nettrust_history", JSON.stringify(updated)); } catch {}
      return updated;
    });
  }, []);

  const handleScanAgain = useCallback(() => {
    setResult(null);
    setFingerprintResult(null);
    setAutoScan(true);
    setState("scanning");
  }, []);

  const handleViewHistoryResult = useCallback((entry: HistoryEntry) => {
    setResult(entry.result);
    setFingerprintResult(null);
    setState("results");
    setActiveTab("scan");
  }, []);

  const handleGoToScan = useCallback(() => {
    setActiveTab("scan");
  }, []);

  const showToast = useCallback((message: string, type: "success" | "warning" = "success") => {
    setToast({ message, type });
  }, []);

  const handleClearHistory = useCallback(() => {
    setHistory([]);
    localStorage.removeItem("nettrust_history");
    showToast("Scan history cleared");
  }, [showToast]);

  const handleClearFingerprints = useCallback(() => {
    clearFingerprints();
    showToast("Network fingerprints cleared");
  }, [showToast]);

  const handleEraseAllData = useCallback(() => {
    setHistory([]);
    setResult(null);
    setFingerprintResult(null);
    setState("idle");
    clearFingerprints();
    localStorage.removeItem("nettrust_history");
    localStorage.removeItem("nettrust_consent");
    localStorage.removeItem("nettrust_consent_date");
    setHasConsent(false);
  }, []);

  const handleExportReport = useCallback(() => {
    if (!result) return;
    const report = generateReport(result);

    if (navigator.share) {
      navigator.share({ title: "NetTrust Scan Report", text: report }).catch(() => {
        navigator.clipboard.writeText(report);
        showToast("Report copied to clipboard");
      });
    } else {
      navigator.clipboard.writeText(report);
      showToast("Report copied to clipboard");
    }
  }, [result, showToast]);

  // Count active threats for nav badge
  const threatCount = result
    ? result.checks.filter(c => c.passed === false).length
    : 0;

  // Consent screen (first launch)
  if (!hasConsent) {
    return <ConsentScreen onAccept={() => setHasConsent(true)} />;
  }

  if (showSplash) {
    return <SplashScreen onDismiss={handleSplashDismiss} />;
  }

  return (
    <div className="min-h-screen flex justify-center bg-background">
      {toast && (
        <Toast message={toast.message} type={toast.type} onDone={() => setToast(null)} />
      )}
      <div className="w-full max-w-[430px] min-h-screen flex flex-col relative">
        {/* Header */}
        <header className="relative flex items-center justify-center gap-2 pt-12 pb-3 px-6">
          <div className="flex items-center gap-2 select-none">
            <ShieldAlert size={20} className="text-primary" strokeWidth={2.5} />
            <h1 className="text-lg font-bold tracking-tight text-foreground">
              Net<span className="text-primary">Trust</span>
            </h1>
            <span className="text-[9px] font-mono uppercase tracking-wider text-primary/40 ml-1">v4.0</span>
          </div>
        </header>

        {/* Content */}
        <main className="flex-1 flex flex-col px-5 overflow-y-auto">
          {activeTab === "scan" && (
            <>
              {(state === "idle" || state === "scanning") && (
                <div className="flex-1 flex flex-col items-center justify-center gap-2">
                  {state === "idle" && (
                    <p className="text-muted-foreground/60 text-xs font-mono mb-6 text-center tracking-wide">
                      Is this WiFi safe?
                    </p>
                  )}
                  <ScanButton onScanComplete={handleScanComplete} autoStart={autoScan} />
                </div>
              )}

              {state === "results" && result && (
                <ResultsScreen
                  result={result}
                  onScanAgain={handleScanAgain}
                  fingerprintResult={fingerprintResult}
                />
              )}
            </>
          )}

          {activeTab === "history" && (
            <HistoryScreen
              entries={history}
              onViewResult={handleViewHistoryResult}
              onGoToScan={handleGoToScan}
            />
          )}

          {activeTab === "more" && (
            <MoreScreen
              onClearHistory={handleClearHistory}
              onClearFingerprints={handleClearFingerprints}
              onExportReport={handleExportReport}
              onEraseAllData={handleEraseAllData}
              historyCount={history.length}
              hasResults={result !== null}
            />
          )}
        </main>

        {/* Bottom Nav */}
        <div className="sticky bottom-0">
          <BottomNav
            activeTab={activeTab}
            onTabChange={setActiveTab}
            threatCount={state === "results" ? threatCount : undefined}
          />
        </div>
      </div>
    </div>
  );
};

export default Index;
