import { useState, useCallback } from "react";
import { ShieldAlert } from "lucide-react";
import ScanButton from "@/components/ScanButton";
import ResultsScreen from "@/components/ResultsScreen";
import HistoryScreen from "@/components/HistoryScreen";
import MoreScreen from "@/components/MoreScreen";

import SplashScreen from "@/components/SplashScreen";
import ConsentScreen from "@/components/ConsentScreen";
import OnboardingScreen from "@/components/OnboardingScreen";
import ShareCard from "@/components/ShareCard";
import Toast from "@/components/Toast";
import BottomNav from "@/components/BottomNav";
import { ScanResult } from "@/lib/mockData";
import { createFingerprint, compareAndStoreFingerprint, FingerprintComparison, clearFingerprints } from "@/lib/networkFingerprint";
import type { HistoryEntry } from "@/components/HistoryScreen";

type AppState = "idle" | "scanning" | "results";

function generateReport(result: ScanResult): string {
  const lines: string[] = [];
  const ssid = result.wifiCurrentConnection?.ssid || result.networkName;
  lines.push("═══════════════════════════════════════════════");
  lines.push("  NETTRUST SCAN REPORT");
  lines.push("═══════════════════════════════════════════════");
  lines.push("");
  lines.push(`Network:      ${ssid}`);
  lines.push(`Type:         ${result.networkType}`);
  lines.push(`Trust Score:  ${result.trustScore}/100`);
  if (result.publicIp) lines.push(`Public IP:    ${result.publicIp}`);
  if (result.ipReputation) {
    lines.push(`ISP:          ${result.ipReputation.org}`);
    lines.push(`Location:     ${result.ipReputation.city}, ${result.ipReputation.country}`);
    lines.push(`IP Type:      ${result.ipReputation.ipType}`);
  }
  lines.push(`Scanned:      ${new Date().toISOString()}`);
  lines.push("");

  const failed = result.checks.filter(c => c.passed === false);
  const warnings = result.checks.filter(c => c.passed === null);
  const passed = result.checks.filter(c => c.passed === true);

  if (failed.length > 0) {
    lines.push(`── PROBLEMS FOUND (${failed.length}) ─────────────────────`);
    failed.forEach(c => {
      lines.push(`  ✗ ${c.name}`);
      lines.push(`    ${c.status}`);
      if (c.evidence) {
        Object.entries(c.evidence).forEach(([k, v]) => {
          lines.push(`    ${k}: ${v}`);
        });
      }
      lines.push("");
    });
  }
  if (warnings.length > 0) {
    lines.push(`── COULDN'T VERIFY (${warnings.length}) ──────────────────`);
    warnings.forEach(c => {
      lines.push(`  ⚠ ${c.name}: ${c.status}`);
    });
    lines.push("");
  }
  lines.push(`── PASSED (${passed.length}) ────────────────────────────`);
  passed.forEach(c => lines.push(`  ✓ ${c.name}`));
  lines.push("");
  lines.push("───────────────────────────────────────────────");
  lines.push("Generated by NetTrust · netrust.lovable.app");
  return lines.join("\n");
}

const Index = () => {
  const [hasConsent, setHasConsent] = useState(() => {
    return localStorage.getItem("nettrust_consent") === "true";
  });
  const [hasOnboarded, setHasOnboarded] = useState(() => {
    return localStorage.getItem("nettrust_onboarded") === "true";
  });
  const [showSplash, setShowSplash] = useState(true);
  const [state, setState] = useState<AppState>("idle");
  const [activeTab, setActiveTab] = useState("scan");
  const [result, setResult] = useState<ScanResult | null>(null);
  const [fingerprintResult, setFingerprintResult] = useState<FingerprintComparison | null>(null);
  const [autoScan, setAutoScan] = useState(false);
  const [showShare, setShowShare] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "warning" } | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>(() => {
    try {
      const stored = localStorage.getItem("nettrust_history");
      if (stored) {
        const parsed = JSON.parse(stored);
        return parsed.map((e: HistoryEntry & { timestamp: string }) => ({ ...e, timestamp: new Date(e.timestamp) }));
      }
    } catch {}
    return [];
  });

  const handleSplashDismiss = useCallback(() => {
    setShowSplash(false);
    if (hasOnboarded) {
      setAutoScan(true);
      setState("scanning");
    }
  }, [hasOnboarded]);

  const handleOnboardingComplete = useCallback(() => {
    setHasOnboarded(true);
    setAutoScan(true);
    setState("scanning");
  }, []);

  const handleScanComplete = useCallback((scanResult: ScanResult) => {
    setResult(scanResult);
    setState("results");
    setAutoScan(false);

    const ssid = scanResult.wifiCurrentConnection?.ssid || scanResult.networkName;
    const fp = createFingerprint(
      ssid,
      scanResult.publicIp,
      scanResult.checks,
      scanResult.ipReputation ? {
        org: scanResult.ipReputation.org,
        asn: scanResult.ipReputation.asn,
        city: scanResult.ipReputation.city,
      } : null,
      scanResult.trustScore,
    );
    const comparison = compareAndStoreFingerprint(fp);
    setFingerprintResult(comparison);

    const newEntry: HistoryEntry = {
      id: crypto.randomUUID(),
      result: scanResult,
      timestamp: new Date(),
    };
    setHistory((prev) => {
      const updated = [newEntry, ...prev].slice(0, 50);
      try { localStorage.setItem("nettrust_history", JSON.stringify(updated)); } catch {}
      return updated;
    });
  }, []);

  const handleScanAgain = useCallback(() => {
    setResult(null);
    setFingerprintResult(null);
    setAutoScan(true);
    setState("scanning");
  }, []);

  const handleViewHistoryResult = useCallback((entry: HistoryEntry) => {
    setResult(entry.result);
    setFingerprintResult(null);
    setState("results");
    setActiveTab("scan");
  }, []);

  const handleGoToScan = useCallback(() => {
    setActiveTab("scan");
  }, []);

  const showToast = useCallback((message: string, type: "success" | "warning" = "success") => {
    setToast({ message, type });
  }, []);

  const handleClearHistory = useCallback(() => {
    setHistory([]);
    localStorage.removeItem("nettrust_history");
    showToast("Scan history cleared");
  }, [showToast]);

  const handleClearFingerprints = useCallback(() => {
    clearFingerprints();
    showToast("Network fingerprints cleared");
  }, [showToast]);

  const handleEraseAllData = useCallback(() => {
    setHistory([]);
    setResult(null);
    setFingerprintResult(null);
    setState("idle");
    clearFingerprints();
    localStorage.removeItem("nettrust_history");
    localStorage.removeItem("nettrust_consent");
    localStorage.removeItem("nettrust_consent_date");
    localStorage.removeItem("nettrust_onboarded");
    setHasConsent(false);
    setHasOnboarded(false);
  }, []);

  const handleExportReport = useCallback(() => {
    if (!result) return;
    setShowShare(true);
  }, [result]);

  const threatCount = result
    ? result.checks.filter(c => c.passed === false).length
    : 0;

  if (!hasConsent) {
    return <ConsentScreen onAccept={() => setHasConsent(true)} />;
  }

  if (showSplash) {
    return <SplashScreen onDismiss={handleSplashDismiss} />;
  }

  if (!hasOnboarded) {
    return <OnboardingScreen onComplete={handleOnboardingComplete} />;
  }

  return (
    <div className="min-h-screen flex justify-center bg-background">
      {toast && (
        <Toast message={toast.message} type={toast.type} onDone={() => setToast(null)} />
      )}
      {showShare && result && (
        <ShareCard result={result} onClose={() => setShowShare(false)} onToast={(msg) => { setShowShare(false); showToast(msg); }} />
      )}
      <div className="w-full max-w-[430px] min-h-screen flex flex-col relative">
        <header className="relative flex items-center justify-center gap-2 pt-12 pb-3 px-6">
          <div className="flex items-center gap-2 select-none">
            <ShieldAlert size={20} className="text-primary" strokeWidth={2.5} aria-hidden="true" />
            <h1 className="text-lg font-bold tracking-tight text-foreground">
              Net<span className="text-primary">Trust</span>
            </h1>
          </div>
        </header>

        <main className="flex-1 flex flex-col px-5 overflow-y-auto" role="main">
          {activeTab === "scan" && (
            <>
              {(state === "idle" || state === "scanning") && (
                <div className="flex-1 flex flex-col items-center justify-center gap-2">
                  {state === "idle" && (
                    <p className="text-muted-foreground/60 text-sm mb-6 text-center">
                      Is this WiFi safe to use?
                    </p>
                  )}
                  <ScanButton onScanComplete={handleScanComplete} autoStart={autoScan} />
                </div>
              )}

              {state === "results" && result && (
                <ResultsScreen
                  result={result}
                  onScanAgain={handleScanAgain}
                  fingerprintResult={fingerprintResult}
                  onShare={() => setShowShare(true)}
                />
              )}
            </>
          )}

          {activeTab === "tools" && <ToolsScreen />}

          {activeTab === "history" && (
            <HistoryScreen
              entries={history}
              onViewResult={handleViewHistoryResult}
              onGoToScan={handleGoToScan}
            />
          )}

          {activeTab === "more" && (
            <MoreScreen
              onClearHistory={handleClearHistory}
              onClearFingerprints={handleClearFingerprints}
              onExportReport={handleExportReport}
              onEraseAllData={handleEraseAllData}
              historyCount={history.length}
              hasResults={result !== null}
            />
          )}
        </main>

        <div className="sticky bottom-0">
          <BottomNav
            activeTab={activeTab}
            onTabChange={setActiveTab}
            threatCount={state === "results" ? threatCount : undefined}
          />
        </div>
      </div>
    </div>
  );
};

export default Index;
